
	CREATE TABLE IF NOT EXISTS BALANCE (
	id BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	addr VARCHAR(40) NOT NULL COMMENT '地址',
	asset_id BIGINT(20) NOT NULL COMMENT '资产ID',
	amount BIGINT(20) NOT NULL COMMENT '总额',
	updated DATETIME NOT NULL COMMENT '更新时间',	
	UNIQUE KEY uniq_addr_asset_id (addr,asset_id)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='资产表';

	CREATE TABLE IF NOT EXISTS block (
	id BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	hash VARCHAR(40) NOT NULL COMMENT '区块哈希',
	pre_hash VARCHAR(40) NOT NULL COMMENT '前一个区块哈希',
	state_hash VARCHAR(40) NOT NULL COMMENT 'state哈希',
	created DATETIME NOT NULL COMMENT '创建时间',
	nonce BIGINT(20) UNSIGNED NOT NULL COMMENT '区块nonce',
	txs_merkle_hash VARCHAR(40) NOT NULL COMMENT '交易merkle哈希',	
	height BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '区块高度',
	UNIQUE KEY uniq_hash (hash)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='区块表';

	CREATE TABLE IF NOT EXISTS transaction (
	id BIGINT(20) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	from_chain VARCHAR(40) NOT NULL COMMENT '发送链',
	to_chain VARCHAR(40) NOT NULL COMMENT '接受链',
	type TINYINT NOT NULL COMMENT '交易类型',
	nonce BIGINT(20) NOT NULL COMMENT '交易nonce',
	sender VARCHAR(40) NOT NULL COMMENT '发送地址',
	receiver VARCHAR(40) NOT NULL COMMENT '接收地址',
	asset_id BIGINT(20) NOT NULL COMMENT '资产ID',
	amount BIGINT(20) NOT NULL COMMENT '总额',
	fee BIGINT(20) NOT NULL COMMENT '手续费',
	signature VARCHAR(255) NOT NULL COMMENT '签名',
	created DATETIME NOT NULL COMMENT '创建时间',
	payload TEXT NOT NULL COMMENT '负载字段',
	hash VARCHAR(40) NOT NULL COMMENT '交易hash',
	height BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '所在区块高度',
	contract_addr VARCHAR(40) NOT NULL COMMENT '合约地址',
	contract_code TEXT NOT NULL COMMENT '合约代码',
	contract_params VARCHAR(255) NOT NULL COMMENT '合约参数',
	UNIQUE KEY uniq_hash (hash)
)ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COMMENT='交易表';
